## Travis CI Integration

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild JPBetley.Foundry.sln
  - nunit-console JPBetley.Foundry.Test/bin/Debug/JPBetley.Foundry.Test.dll
